"""
Django settings for thinkingcap project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f#ong^2euz5kcnk6)46%8)hn51sm($23is7rx&go$d@wmfw-+n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'onthisday',
    'colors',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'thinkingcap',
        'USER': 'postgres',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    },

}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# ======================== #
#       API SETTINGS       #
# ======================== #
API_BASE_URL = "http://localhost:8000/api/v1/"

# ======================== #
#     APP SPECIFIC KEYS    #
# ======================== #

#          colors
# ==========================
# API TOKEN used for colors app
API_TOKEN_COLORS = '123'
API_LIMIT_COLORS = 500

# taken from https://simple.wikipedia.org/wiki/List_of_colors
COLOR_LIST = [
    "Amaranth","Amber","Amethyst","Apricot","Aquamarine","Azure","Baby blue","Beige","Black","Blue","Blue-green",
    "Blue-violet","Blush","Bronze","Brown","Burgundy","Byzantium","Carmine","Cerise","Cerulean","Champagne",
    "Chartreuse green","Chocolate","Cobalt blue","Coffee","Copper","Coral","Crimson","Cyan","Desert sand",
    "Electric blue","Emerald","Erin","Gold","Gray","Green","Harlequin","Indigo","Ivory","Jade","Jungle green",
    "Lavender","Lemon","Lilac","Lime","Magenta","Magenta rose","Maroon","Mauve","Navy blue","Ocher","Olive","Orange",
    "Orange-red","Orchid","Peach","Pear","Periwinkle","Persian blue","Pink","Plum","Prussian blue","Puce","Purple",
    "Raspberry","Red","Red-violet","Rose","Ruby","Salmon","Sangria","Sapphire","Scarlet","Silver","Slate gray",
    "Spring bud","Spring green","Tan","Taupe","Teal","Turquoise","Violet","Viridian","White","Yankees Blue","Yellow"
]

#        onthisday
# ==========================
API_TOKEN_ONTHISDAY = '456'
