# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('colors', models.ManyToManyField(related_name='colorcase', to='colors.Color')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
                ('offset', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('related_to', models.IntegerField(null=True)),
            ],
        ),
    ]
