# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 02:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_colorcase_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingColorCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_before', models.TextField()),
                ('original_word', models.CharField(blank=True, max_length=100, null=True)),
                ('context_after', models.TextField()),
                ('consensus', models.BooleanField(default=False)),
                ('votes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=2)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.TextField(blank=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('hide', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colors.Color')),
            ],
        ),
    ]
